### ISSUE TITLE
微信转发消息的call有咋找呀

### ISSUE THREAD

**Issue by as614001** [Hellmessage/pcwechathook#1]

**Comment by hb5813** [comment]
从up主教的找发送消息日志的地方按堆栈回溯，可以找到一个传入消息ID和收件人wxid的地方

**Comment by as614001** [comment]
> 
> 
> 从up主教的找发送消息日志的地方按堆栈回溯，可以找到一个传入消息ID和收件人wxid的地方

前些天找到了，在这个call有个edx看不懂是啥。

**Comment by hb5813** [comment]
549D58F9   .  52            push edx                                 ;  似乎是一个固定数值0x5000100
549D58FA   .  50            push eax                                 ;  消息ID
549D58FB   .  83EC 14       sub esp,0x14                             ;  留出五个4字节放wxid结构体
549D58FE   .  8BCC          mov ecx,esp
549D5900   .  6A FF         push -0x1                                ;  固定的参数
549D5902   .  C701 00000000 mov dword ptr ds:[ecx],0x0
549D5908   .  C741 04 00000>mov dword ptr ds:[ecx+0x4],0x0
549D590F   .  C741 08 00000>mov dword ptr ds:[ecx+0x8],0x0
549D5916   .  C741 0C 00000>mov dword ptr ds:[ecx+0xC],0x0
549D591D   .  C741 10 00000>mov dword ptr ds:[ecx+0x10],0x0
549D5924   .  FF36          push dword ptr ds:[esi]                  ;  wxid
549D5926   .  E8 A5755000   call WeChatWi.54EDCED0                   ;  把wxid包装成结构体放到上面堆栈预留的5个字节中
549D592B   .  E8 C0DC3100   call WeChatWi.54CF35F0                   ;  转发最顶层，堆栈前五位是消息结构体，然后第六位是ID

**Comment by as614001** [comment]
我这分析的是 0x5000500 无论重启还是重开。有时是有值有时是0. 3.3.115版本。

**Comment by as614001** [comment]
@hb5813

**Comment by as614001** [comment]
整个转发dll其实前两天也完成了。留下的困惑就是这个。貌似指向一个资源

**Comment by hb5813** [comment]
我也是3.3.115，但地址却稍有区别。这个资源到底是啥我也没弄懂。
